# Generated by Django 3.0.2 on 2020-02-08 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=255)),
                ('lastNamee', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
