# Generated by Django 3.0.2 on 2020-02-08 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='lastNamee',
            new_name='lastName',
        ),
    ]
